# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cobble < Formula
  desc ""
  homepage "https://github.com/jclem/cobble"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jclem/cobble/releases/download/v0.0.8/cobble_0.0.8_macOS_arm64.tar.gz"
      sha256 "c034dde468225f584665d81ea17def33816bb9ea00b0d75d92f4d1bda252c9c5"

      def install
        bin.install "cobble"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jclem/cobble/releases/download/v0.0.8/cobble_0.0.8_macOS_64-bit.tar.gz"
      sha256 "417156bd560a321775221fd22227626f6c7b1abee25275e2d59092fee7a0724e"

      def install
        bin.install "cobble"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclem/cobble/releases/download/v0.0.8/cobble_0.0.8_Linux_arm64.tar.gz"
      sha256 "271a1e7d34e3a1cfaac96d9b4ebbf150f5d88082686883f49ef343b970cf4516"

      def install
        bin.install "cobble"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jclem/cobble/releases/download/v0.0.8/cobble_0.0.8_Linux_64-bit.tar.gz"
      sha256 "577fe25e90687ba50c8279b49fb83871d6a5b214f7f1842bbafef97feb962d63"

      def install
        bin.install "cobble"
      end
    end
  end

  test do
    system "#{bin}/cobble --version"
  end
end
