# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cobble < Formula
  desc ""
  homepage "https://github.com/jclem/cobble"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jclem/cobble/releases/download/v0.0.9/cobble_0.0.9_macOS_arm64.tar.gz"
      sha256 "80c67a264aac0398f01bba7ce4552e40a44c8f1dce76580f7292856f728ca535"

      def install
        bin.install "cobble"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jclem/cobble/releases/download/v0.0.9/cobble_0.0.9_macOS_64-bit.tar.gz"
      sha256 "b290784b481b4ebf72ab01d1f8e7da7c03e0519b46a0ad1128aae550ff407888"

      def install
        bin.install "cobble"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclem/cobble/releases/download/v0.0.9/cobble_0.0.9_Linux_arm64.tar.gz"
      sha256 "ac1203bd5b51ec9def39d6bf57d6dbcf2d0b5b2d486a864ceba6b484f9f9c314"

      def install
        bin.install "cobble"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jclem/cobble/releases/download/v0.0.9/cobble_0.0.9_Linux_64-bit.tar.gz"
      sha256 "6f8c3c0b2f256f9d3022278ba0e60661370d8229140cf86d4fe301ac2bc46555"

      def install
        bin.install "cobble"
      end
    end
  end

  test do
    system "#{bin}/cobble --version"
  end
end
