# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Konk < Formula
  desc ""
  homepage "https://github.com/jclem/konk"
  version "0.27.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jclem/konk/releases/download/v0.27.1/konk_0.27.1_macOS_arm64.tar.gz"
      sha256 "9784b5b9e5fb2aaf5d4e49189faa41299a50e2b72aebf3d80a9183c346b060fa"

      def install
        bin.install "konk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jclem/konk/releases/download/v0.27.1/konk_0.27.1_macOS_64-bit.tar.gz"
      sha256 "386d5df29f5244e2fad6ef9705b9e6c43f2b54a54f328150783d070e6590d31e"

      def install
        bin.install "konk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclem/konk/releases/download/v0.27.1/konk_0.27.1_Linux_arm64.tar.gz"
      sha256 "d34a04ccdc0e5c609d165a69309b3f5f527fba2202fb077181055486349d9a86"

      def install
        bin.install "konk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jclem/konk/releases/download/v0.27.1/konk_0.27.1_Linux_64-bit.tar.gz"
      sha256 "321fa3393b46619a9232b1dd511ad7d51276abc4d627d316c9d0500a22b5bd9e"

      def install
        bin.install "konk"
      end
    end
  end

  test do
    system "#{bin}/konk --version"
  end
end
