# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Konk < Formula
  desc ""
  homepage "https://github.com/jclem/konk"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jclem/konk/releases/download/v0.19.0/konk_0.19.0_macOS_arm64.tar.gz"
      sha256 "1ae9b977acd974b0a00fdeb269141aaab949ecce7209fdf73f857e435ecd8a6a"

      def install
        bin.install "konk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jclem/konk/releases/download/v0.19.0/konk_0.19.0_macOS_64-bit.tar.gz"
      sha256 "849967b8eb2eec800f40c09eeace1e08078334f2966c8d2ed0e58930b79e0468"

      def install
        bin.install "konk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclem/konk/releases/download/v0.19.0/konk_0.19.0_Linux_arm64.tar.gz"
      sha256 "54b70ff8a1ba9148dc9aaaa84d01fa73c10de4254eacd3fa76294c1a764fba26"

      def install
        bin.install "konk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jclem/konk/releases/download/v0.19.0/konk_0.19.0_Linux_64-bit.tar.gz"
      sha256 "34b3e60a83c52e2798a587eb130c6e19a8929381c4887f345529f10d8972ded3"

      def install
        bin.install "konk"
      end
    end
  end

  test do
    system "#{bin}/konk --version"
  end
end
